Phn5
UTRA-ART/Photon pull request #15
Opened 2021-03-27 16:16 UTC by psantasr

---
title: PHN5 - RGBD Camera
---

### Description ###

Added the RGBD camera plug-in. Spawns in RViz and Gazebo. 

### Issues ###

Still unsure how to get it to look properly on gazebo.

### Notes ###

Looking for feedback to incorporate in the code and better it. Source of current code - Caffeine ZED Camera + MJ codes for the lidar plug-in in order to understand how to do a plug in

2021-03-27 16:52 UTC, erickmu1 requested changes

2021-03-27 16:52 UTC, erickmu1 commented on description/rviz/rgbd_camera.rviz
> +  - Class: rviz/Tool Properties
remove this rviz file and make respective changes in `view.rviz`

2021-03-27 16:52 UTC, erickmu1 commented on description/urdf/constants.xacro
>      <!-- IMU -->
new line (nice spacing)

2021-03-27 16:52 UTC, erickmu1 commented on description/urdf/cybertruck.urdf.xacro
> +        <origin xyz="${body_length/2 - camera_width} 0 ${camera_height / 2.0}" rpy="0 ${camera_pitch} 0"/>
replace `2` with `2.0`

2021-03-27 17:25 UTC, EsteBran approved these changes
Reviewed, everything seems good, just a few newlines.

2021-03-27 17:25 UTC, EsteBran commented on description/launch/rgbd_camera.launch
> +</launch>
add newline

2021-03-27 17:25 UTC, EsteBran commented on description/launch/spawn.launch
>  </launch>
add newline

2021-03-27 17:25 UTC, EsteBran commented on description/launch/simulate.launch
>  </launch>
add newline

2021-03-27 17:25 UTC, EsteBran commented on description/urdf/cybertruck.urdf.xacro
> +        <origin xyz="${body_length/2 - camera_width} 0 ${camera_height / 2.0}" rpy="0 ${camera_pitch} 0"/>
Add newline

2021-03-27 18:05 UTC, kishya requested changes
A reminder to erase the hello.launch file

2021-03-27 18:05 UTC, kishya commented on description/urdf/cybertruck.urdf.xacro
> +            <box size="${camera_width} ${camera_length} ${camera_height}"/>
Formatting: Tab before <box

2021-03-27 18:05 UTC, kishya commented on description/launch/simulate.launch
> +    <!-- Camera Plug-in -->
the plugin is called twice: once from simulate.launch and once from spawn.launch.
spawn.launch is called in simulate.launch.

2021-03-27 18:05 UTC, kishya commented on description/launch/spawn.launch
> +        <include file="$(find description)/launch/rgbd_camera.launch">
Maybe add a comment explaining what this code block does

2021-04-03 16:44 UTC, cuevasm2 commented on description/urdf/inertias.xacro
> +        <inertia
Make the start `<inertia>` and end with `<\inertia>` instead of `/>`

2021-04-24 03:29 UTC, erickmu1 approved these changes
Please refer to the linked issue where I show a screenshot that shows the left/right stereo images align with Photon in RViz. At this point everything works as expected.

Note there is no depth images to view unless we add another node to perform `disparity --> depth` conversion. We did this in Caffeine using RTAB (which we also used for visual odom), so this can be deferred.

Also note that the `pointclouds` are off by default (since they are expensive to render)

2021-04-24 03:32 UTC, merged